backend:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/**'
          - 'package.json'
          - 'package-lock.json'
          - 'test/**'

docker:
  - changed-files:
      - any-glob-to-any-file:
          - 'Dockerfile'
          - '.dockerignore'

ci:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/**'

deployment:
  - changed-files:
      - any-glob-to-any-file:
          - 'manifests/**'
          - 'chart/**'

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.md'
