apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-extension-backend-api
  namespace: glueops-core
  labels:
    app.kubernetes.io/name: argocd-extension-backend-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-extension-backend-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-extension-backend-api
    spec:
      containers:
        - name: argocd-extension-backend-api
          image: ghcr.io/glueops/argocd-extension-backend-api:v.0.0.1@sha256:fefde17e4a2223eea3a94ab4a864cfb40a340c6ce8b3b3ad578ef5a0154adfe3
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: PORT
              value: "8000"
            - name: PROMETHEUS_BASE_URL
              value: "http://kps-prometheus.glueops-core-kube-prometheus-stack.svc.cluster.local:9090"
            - name: TEMPO_BASE_URL
              value: ""
            - name: LOG_LEVEL
              value: "INFO"
            - name: GRAFANA_BASE_URL
              value: "https://grafana.nonprod.venus.onglueops.rocks"
            - name: VAULT_BASE_URL
              value: "https://vault.nonprod.venus.onglueops.rocks"
            - name: DEPLOYMENT_CONFIG_REPO_URL
              value: "https://github.com/GlueOps/deployment-configurations"
            - name: ALLOWED_NAMESPACES
              value: "nonprod"
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: argocd-extension-backend-api
  namespace: glueops-core
  labels:
    app.kubernetes.io/name: argocd-extension-backend-api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: argocd-extension-backend-api
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP